from fabric import Connection
c = Connection('22951266-lab7-fabric')
result = c.run('uname -s')
result = c.sudo('apt-get update')
result = c.sudo('apt-get upgrade')
result = c.sudo('apt-get install python3-venv')
result = c.sudo('apt install python3-pip')
result = c.sudo('pip install django')
result = c.sudo('apt-get install git-core')
res = c.run('git config --global user.name Wolfgang1208')
res = c.run('git config --global user.email Wolfgang1208@outlook.com')
res = c.run('git config --list')
#res = c.sudo('ssh-keygen -t rsa -C "Wolfgang1208@outlook.com"')
res = c.sudo('cat /root/.ssh/id_rsa.pub')
res = c.sudo('apt install nginx')
